# permissions for end users to view ethswitches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ethswitch-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - ethswitches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - ethswitches/status
  verbs:
  - get
