# permissions for end users to edit ethswitches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ethswitch-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - ethswitches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - ethswitches/status
  verbs:
  - get
