# permissions for end users to edit fcswitches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fcswitch-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - fcswitches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - fcswitches/status
  verbs:
  - get
