# permissions for end users to view fcswitches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fcswitch-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - fcswitches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - fcswitches/status
  verbs:
  - get
