# permissions for end users to edit infrastructurepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infrastructurepool-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - infrastructurepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - infrastructurepools/status
  verbs:
  - get
