# permissions for end users to view infrastructurepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infrastructurepool-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - infrastructurepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - infrastructurepools/status
  verbs:
  - get
