
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - ethswitch
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - ethswitch/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.example.com
  resources:
  - ethswitches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - ethswitches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.example.com
  resources:
  - fcswitch
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - fcswitch/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.example.com
  resources:
  - fcswitches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - fcswitches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.example.com
  resources:
  - infrastructurepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - infrastructurepools/status
  verbs:
  - get
  - patch
  - update
